# netty ??
netty:
  # boss????
  boss: 4
  # worker????
  worker: 2
  # ??????
  timeout: 6000
  # ??????
  port: 9999
  # ???????
  portSalve: 18026
  # ?????
  host: 127.0.0.1

server:
  port: 8080
